export const INIT_MODEL = "INIT_MODEL";
export const SET_LOADING = "SET_LOADING";

export const ADD_POSITIVE = "ADD_POSITIVE";
export const SET_POSITIVE = "SET_POSITIVE";
export const REMOVE_POSITIVE = "REMOVE_POSITIVE";

export const ADD_NEGATIVE = "ADD_NEGATIVE";
export const SET_NEGATIVE = "SET_NEGATIVE";
export const REMOVE_NEGATIVE = "REMOVE_NEGATIVE";

export const ADD_SEEN = "ADD_SEEN";
export const SET_SEEN = "SET_SEEN";
export const UPDATE_SEEN = "UPDATE_SEEN";

export const ADD_IMAGES = "ADD_IMAGES";
export const SET_IMAGES = "SET_IMAGES";

export const SET_MEDIA_INFO = "SET_MEDIA_INFO";

export const RESET_MODEL = "RESET_MODEL";

export const SET_IMAGE_FOR_PROJECTION = "SET_IMAGE_FOR_PROJECTION";
export const SET_POSITIVE_PROJECTION = "SET_POSITIVE_PROJECTION";
export const SET_NEGATIVE_PROJECTION = "SET_NEGATIVE_PROJECTION";

export const REPLACE_IMAGE = "REPLACE_IMAGE";

export const SET_MODE = "SET_MODE";
