export const SET_DEVICES = "SET_DEVICES";
export const ADD_DEVICE = "ADD_DEVICES";
export const CLEAR_DEVICES = "CLEAR_DEVICES";
export const SET_SELECTED_DEVICE = "SET_SELECTED_DEVICE";
export const SET_LOADING = "SET_LOADING";
export const SET_HISTORY = "SET_HISTORY";
